# Generated by Django 4.2.5 on 2023-09-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_establishment_menu_customer_has_reservation_tables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='table_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
