# Generated by Django 4.2.5 on 2023-09-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tables_table_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tables',
            options={'verbose_name_plural': 'about'},
        ),
    ]
