# Generated by Django 4.2.5 on 2023-09-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tables_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tables',
            options={'verbose_name_plural': 'Tables'},
        ),
    ]
