# Generated by Django 4.2.5 on 2023-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tables_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='reservaion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
