# Generated by Django 4.2.5 on 2023-09-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tables_reservaion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='table_number',
            field=models.IntegerField(unique=True),
        ),
    ]
