# Generated by Django 4.2.5 on 2023-09-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_tables_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.establishment'),
        ),
    ]
