# Generated by Django 4.2.5 on 2023-09-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_tables_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='table_number',
            field=models.IntegerField(),
        ),
    ]
