# Generated by Django 4.2.5 on 2023-09-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_dish_options_rename_dish_dish_name_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tables',
            old_name='reservaion_time',
            new_name='reservation_time',
        ),
    ]
