# Generated by Django 4.2.5 on 2023-09-19 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dish'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.establishment'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tables'),
        ),
    ]
